# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1ce4d4ad-0f49-4410-bc82-6d7379295e25";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/15C7-1939";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/edf2b4d5-33fe-40ae-8aa7-f871063d3639";
    fsType = "ext4";
  };

  fileSystems."/mnt/samba_share/Documentos" = {
    device = "//192.168.0.8/Documentos";
    fsType = "cifs";
  };

  fileSystems."/mnt/samba_share/movies" = {
    device = "//192.168.0.8/movies";
    fsType = "cifs";
  };

  fileSystems."/mnt/samba_share/Music" = {
    device = "//192.168.0.8/Music";
    fsType = "cifs";
  };

  fileSystems."/mnt/samba_share/titan" = {
    device = "//192.168.0.8/titan";
    fsType = "cifs";
  };

  fileSystems."/mnt/samba_share/tvseries" = {
    device = "//192.168.0.8/tvseries";
    fsType = "cifs";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/ffc2e9a3-e7bc-4ad6-b51b-ecf1e4be4b7c"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
