# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/567782d0-9c7f-4150-a00c-24b4a180a7f6";
    fsType = "ext4";
  };

  fileSystems."/mnt/samba_share/Documentos" = {
    device = "systemd-1";
    fsType = "autofs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/15C7-1939";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/edf2b4d5-33fe-40ae-8aa7-f871063d3639";
    fsType = "ext4";
  };

  fileSystems."/mnt/samba_share/Documentos" = {
    device = "//192.168.0.8/Documentos";
    fsType = "cifs";
  };

  fileSystems."/mnt/samba_share/movies" = {
    device = "//192.168.0.8/movies";
    fsType = "cifs";
  };

  fileSystems."/mnt/samba_share/Music" = {
    device = "//192.168.0.8/Music";
    fsType = "cifs";
  };

  fileSystems."/mnt/samba_share/titan" = {
    device = "//192.168.0.8/titan";
    fsType = "cifs";
  };

  fileSystems."/mnt/samba_share/tvseries" = {
    device = "//192.168.0.8/tvseries";
    fsType = "cifs";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/ffc2e9a3-e7bc-4ad6-b51b-ecf1e4be4b7c"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
