theme:
  activeBorderColor:
    - '#89dceb'
    - bold
  inactiveBorderColor:
    - '#a6adc8'
  optionsTextColor:
    - '#89b4fa'
  selectedLineBgColor:
    - '#313244'
  selectedRangeBgColor:
    - '#313244'
  cherryPickedCommitBgColor:
    - '#45475a'
  cherryPickedCommitFgColor:
    - '#89dceb'
  unstagedChangesColor:
    - '#f38ba8'
  defaultFgColor:
    - '#cdd6f4'
  searchingActiveBorderColor:
    - '#f9e2af'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
customCommands:
  # Create GitHub pull request
  - key: "<c-r>"
    command: "gh pr create --fill --web"
    context: "global"
    loadingText: "Creating pull request on GitHub"
  # Open PR in the browser
  - key: "G"
    command: "gh pr view --web {{.SelectedLocalBranch.UpstreamBranch}}"
    context: "localBranches"
    description: "Go to MR in gitlab"
    output: log
  # Select a PR number to checkout
  - key: "v"
    context: "localBranches"
    loadingText: "Checking out GitHub Pull Request..."
    command: "gh pr checkout {{.Form.PullRequestNumber}}"
    prompts:
      - type: "menuFromCommand"
        title: "Which PR do you want to check out?"
        key: "PullRequestNumber"
        command: >-
          gh pr list --json number,title,headRefName,updatedAt --template '{{`{{range .}}{{printf "#%v: %s - %s (%s)" .number .title .headRefName (timeago .updatedAt)}}{{end}}`}}'
        filter: '#(?P<number>[0-9]+): (?P<title>.+) - (?P<ref_name>[^ ]+).*'
        valueFormat: '{{.number}}'
        labelFormat: '{{"#" | black | bold}}{{.number | white | bold}} {{.title | yellow | bold}}{{" [" | black | bold}}{{.ref_name | green}}{{"]" | black | bold}}'
  # add gitmojis to the commit
  - command: git commit -m '{{ .Form.emoji }} {{ .Form.message }}'
    context: files
    description: Commit changes using gitmojis
    key: C
    prompts:
      - command: gitmoji list
        filter: ^(.*?)\t(:.*?:)\t(.*)$
        key: emoji
        labelFormat: '{{ .group_1 }} - {{ .group_3 }}'
        title: 'Select a gitmoji:'
        type: menuFromCommand
        valueFormat: '{{ .group_2 }}'
      - key: message
        title: 'Enter a commit message:'
        type: input
